### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by hangjunping** [gaigeshen/ecmybatis-idea#1]
java.lang.NullPointerException
	at me.gaigeshen.idea.ecmybatis.Window.createTableOrColumnNodes(Window.java:190)
	at me.gaigeshen.idea.ecmybatis.Window.access$100(Window.java:49)
	at me.gaigeshen.idea.ecmybatis.Window$LoadAction.actionPerformed(Window.java:247)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:258)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:275)
	at com.intellij.openapi.actionSystem.impl.ActionButton.actionPerformed(ActionButton.java:184)
	at com.intellij.openapi.actionSystem.impl.ActionButton.performAction(ActionButton.java:148)
	at com.intellij.openapi.actionSystem.impl.ActionButton.processMouseEvent(ActionButton.java:410)
	at java.awt.Component.processEvent(Component.java:6313)
	at java.awt.Container.processEvent(Container.java:2237)
	at java.awt.Component.dispatchEventImpl(Component.java:4903)
	at java.awt.Container.dispatchEventImpl(Container.java:2295)
	at java.awt.Component.dispatchEvent(Component.java:4725)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4526)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467)
	at java.awt.Container.dispatchEventImpl(Container.java:2281)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4725)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.awt.EventQueue$4.run(EventQueue.java:735)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:719)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:664)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:363)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by hangjunping** [comment]
jdbc:mysql://localhost:3306/intelligent_clinic?sueSSL=false

**Comment by gaigeshen** [comment]
你安装的插件版本是多少？

**Comment by hangjunping** [comment]
> 
> 
> 你安装的插件版本是多少？

[
![图片](https://user-images.githubusercontent.com/21098819/57186417-68822e80-6f11-11e9-9841-7e986ba72e84.png)
](url)

**Comment by gaigeshen** [comment]
现在最新版本是1.2，你卸载掉重新搜索该插件安装，然后查看是否还存在该问题。

**Comment by hangjunping** [comment]
> 
> 
> 现在最新版本是1.2，你卸载掉重新搜索该插件安装，然后查看是否还存在该问题。

找到的还是1.0

**Comment by gaigeshen** [comment]
![image](https://user-images.githubusercontent.com/7309579/57186448-4dfc8500-6f12-11e9-9a3c-e73109fd9760.png)

你是不是配置了这个，将这里面的地址删除掉，如果配置了的话。

**Comment by gaigeshen** [comment]
@hangjunping 还有问题吗？现在
